FROM python:3.12.2

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-tk

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

CMD [ "python","Ftracer.py" ]